### ISSUE TITLE
Potential not thread-safe behaviour in SynchronizedLifetimeManager

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/abstractions#101]
@pbaravik wrote:

To my mind the code of the method SynchronizedLifetimeManager.GetValue() contains potentially unsafe code:

```
public override object GetValue()
{    
  Monitor.Enter(this.lockObj);    
  object obj2 = this.SynchronizedGetValue();    
  if (obj2 != null)    
  {
    Monitor.Exit(this.lockObj);    
  }    
  return obj2;
}
```

The scenario might be the following:
* the thread captures the lock object 
* SynchronizedGetValue() returns null 
  * I did not find that Recovery would be called if null resolved and thus sync block remains captured
* the thread leaves Unity code 
* the thread is terminated for any reason
* the deadlock situation will take place.

Sample output of WinDbg SOS extensions deadlock analysis (real case):

0:045> !dlk
Examining SyncBlocks...
Scanning for ReaderWriterLock(Slim) instances...
Scanning for holders of ReaderWriterLock locks...
Scanning for holders of ReaderWriterLockSlim locks...
Examining CriticalSections...
Scanning for threads waiting on SyncBlocks...
Scanning for threads waiting on ReaderWriterLock locks...
Scanning for threads waiting on ReaderWriterLocksSlim locks...
Scanning for threads waiting on CriticalSections...
*DEADLOCK DETECTED*
CLR Thread 0x14 is waiting for orphaned SyncBlock 0000000012a3f508 OBJ:000000037f47c750[System.Object]
The lock was orphaned by CLR thread 0x2ef, which has since terminated.
CLR Thread 0x14 is waiting at Microsoft.Practices.Unity.SynchronizedLifetimeManager.GetValue()(+0xb IL,+0x12 Native)

1 deadlock detected.

**Comment by ENikS** [comment]
This will be rather big, breaking change

**Comment by ENikS** [comment]
To use this feature you need to set global timeout like this:
```c#
SynchronizedLifetimeManager.ResolveTimeout = 30000; // 30 sec
```
It will fail with regular `ResolutionFailedException` and inner exception `TimeOutException`

**Comment by smasherprog** [comment]
We are getting deadlocks on this issue above. If the getvalue locks, whose job is it to setvalue? Seems very bad to leave a lock open like this.
Also, the resolvetimeout isnt a valid fix either unfortunately. This just tries to hide the bug under a pile of poop.
If the container isnt being resolved in any reasonable amount of time, then the application is not usable.

**Comment by ENikS** [comment]
In latest version there is a way to set timeout for the lock.
