### ISSUE TITLE
Unity Resolve Issue after Upgrade of Unity.Abstractions from 2.3.1 to 4.1.2

### ISSUE THREAD

**Issue by rinotom** [unitycontainer/abstractions#104]
After upgrading the Unity.Abstractions from 2.3.1 to 4.1.2, we are getting the below error on `Resolve()` using `ParameterOverrides`:

By this upgrade we had change the code below:

```
            T ret = default(T);

            ret = this.Container.Resolve<T>(new ParameterOverrides { { key, value } });

            return ret;

```
and make it as below:

```
            T ret = default(T);

            ret = this.Container.Resolve<T>(new ParameterOverride(key, value));

            return ret;

```

And it is throwing up an error as below during runtime:

```
Unity.ResolutionFailedException
  HResult=0x80131500
  Message=For more information add Diagnostic extension: Container.AddExtension(new Diagnostic())
  Source=Unity.Container
  StackTrace:
   at Unity.UnityContainer.<>c.<.ctor>b__58_1(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)

Inner Exception 1:
InvalidOperationException: Failed to select a constructor for MyClassName
```

**Comment by ENikS** [comment]
Did you try to run it in diagnostic mode as it suggests?

**Comment by rinotom** [comment]
On running with diagnostic mode, I did not get much info on it than the below one line added in the exception:

```
Unity.ResolutionFailedException: 'Failed to select a constructor for MyNameSpace.MyClassName
_____________________________________________________
Exception occurred while:

•resolving type:  'IMyClass' mapped to 'MyClassName'
```

**Comment by ENikS** [comment]
How do you suppose I would help you without any data on types and how you register them. Please provide a unit test that I can run.

I do not have enough information even to make educated guess

**Comment by ENikS** [comment]
Closing for now, feel free to reopen with proper UnitTest

**Comment by talk2rsoni** [comment]
I have the similar issue.  with latest version of Unity. any resolution of it ?

**Comment by ENikS** [comment]
As I said before, I need a unit test that demonstrates the issue. Something I can run in the debugger

**Comment by talk2rsoni** [comment]
np. Eniks, thanks it works, here is the config changes I have done.
![image](https://user-images.githubusercontent.com/3224750/58737460-418b1f80-841f-11e9-9e0c-4da2e1263f37.png)
