### ISSUE TITLE
Document what happened to Unity.Exceptions.IRequiresRecovery

### ISSUE THREAD

**Issue by GSPP** [unitycontainer/abstractions#105]
While upgrading Unity I find that the `Unity.Exceptions.IRequiresRecovery` interface is gone. Please document how to proceed in upgrading code that uses this.

**Comment by ENikS** [comment]
[SynchronizedLifetimeManager](https://github.com/unitycontainer/abstractions/blob/master/src/Lifetime/Abstracts/SynchronizedLifetimeManager.cs) implements [Recover](https://github.com/unitycontainer/abstractions/blob/3974650748a111cc2ae72a150d6656e89680873f/src/Lifetime/Abstracts/SynchronizedLifetimeManager.cs#L90) which is used by [LifetimeStrategy](https://github.com/unitycontainer/container/blob/7618e68951607166926d62b2acf5dce6ea7d89be/src/Strategies/LifetimeStrategy.cs#L64)

**Comment by GSPP** [comment]
Thanks!
