### ISSUE TITLE
Unity.Abstractions 4.1.3 not compatible with Unity.Container 5.10.0 

### ISSUE THREAD

**Issue by mjeanrichard** [unitycontainer/abstractions#106]
I have a project where I installed Unity.AspNet.WebApi 5.10.0 and the Unity.Abstractions 4.1.3.

This gives me strange Resolution exceptions:
```
Exception occurred while:

·resolving type:  'IEnumerable`1'
  for parameter:  'aRechteProviders'
  on constructor:  UpdateRechteStartUpTask(CommandDispatcher aCommandDispatcher, IEnumerable`1 aRechteProviders)
   •resolving type:  'IStartUpTask' mapped to 'UpdateRechteStartUpTask' and registered with name: 'UpdateRechteStartUpTask'
    ·resolving type:  'IStartUpTask[]'
]
   Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context) in C:\projects\container\src\UnityContainer.Resolution.cs:322
   Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides) in C:\projects\container\src\UnityContainer.IUnityContainer.cs:238
   Unity.UnityContainerExtensions.ResolveAll(IUnityContainer container, Type type, ResolverOverride[] resolverOverrides) in C:\projects\abstractions\src\Extensions\Container\UnityContainer.cs:942
   Ingtes.Success.Framework.Host.SuccessHostApplicationBase.RunStartupTasks() +96

[HttpException (0x80004005): Unable to cast object of type 'InvalidValue' to type 'Ingtes.Success.Framework.Modules.Autorisierung.IRechteProvider'.
```

The "InvalidValue" Type is not part of my Code (seems to be coming from LifetimeManager?). As soon as I explicitly install the Unity.Container in Version 5.10.3 (as opposed to 5.10.0 which is included as a Dependency of Unity.AspNet.WebApi) everything works fine. Also if I downgrade UnityAbstractions to 4.1.2 everything works as expected.

Is this expected / known behavior? Were there any breaking changes in Unity.Abstractions 4.1.3?

Unfortuneatly I could not create a simple UnitTest that reproduces this issue.

**Comment by mjeanrichard** [comment]
I just managed to write a test. It seems to have something to do with the SingletonLifetimeManager.

```csharp
namespace UnitTestProject1
{
  public interface ITest
  {
  }

  public class Test : ITest
  {
  }

  public class Test2 : ITest
  {
    private readonly IEnumerable<IInner> _tests;

    public Test2(IEnumerable<IInner> tests)
    {
      _tests = tests;
    }
  }

  public interface IInner
  {
  }

  public class Inner : IInner
  {
  }

  [TestClass]
  public class UnitTest1
  {
    [TestMethod]
    public void TestMethod1()
    {
      UnityContainer container = new UnityContainer();

      container.RegisterType<ITest, Test>(nameof(Test), new TransientLifetimeManager());
      container.RegisterType<ITest, Test2>(nameof(Test2), new TransientLifetimeManager());

      container.RegisterType<IInner, Inner>(nameof(Inner), new SingletonLifetimeManager());

      IEnumerable<ITest> enumerable = container.Resolve<IEnumerable<ITest>>();

      Assert.AreEqual(2, enumerable.Count());
    }
  }
}
```

**Comment by ENikS** [comment]
[Unity.Container 5.10.0](https://www.nuget.org/packages/Unity.Container/5.10.0) works with Unity.Abstractions 4.1.1

If you decided to upgrade the container, why not upgrade Abstractions as well? Perhaps use composite [Unity](https://www.nuget.org/packages/Unity) package to get matching set?

Feel free to reopen if issue persists with matching packages

**Comment by mjeanrichard** [comment]
The Issue happend in the following constellation:

Project A (a Nuget Package) references:
- Unity.AspNet.WebApi 5.10.0

Project B references:
- Unity.Abstractions 4.1.3 (because it needs this directly)
- the Package created in Project A (and therefore gets the reference to Unity.AspNet.WebApi 5.10.0)

With Project B you get the described Error, because nuget will fullfill the dependency on Unity.Container from Unity.AspNet.WebApi with Version 5.10.0).

To me it was just a bit confusing, that there is a breaking change from one Patch Version to the next. But everthing is solved by explicitly referencing the right packages.
