### ISSUE TITLE
Updating to 5.11 from 4.1.3 breaks Unity.Mvc

### ISSUE THREAD

**Issue by PhilPJL** [unitycontainer/abstractions#108]
### Description

After updating from 4.1.3 to 5.11 any web app using Unity.MVC will fail.

### To Reproduce

Create ASP.NET web app.
Update all nuget packages (except bootstrap).
Add Unity.MVC nuget package.
The app will start fine.

Update Unity.Abstractions to 5.11
On starting app we get 

![image](https://user-images.githubusercontent.com/271656/56867585-b44b4a00-69de-11e9-8653-107f80f198b9.png)

**Comment by ENikS** [comment]
Abstractions 5.11.0 requires Container 5.11.0

**Comment by PhilPJL** [comment]
In that case it should be offered as an update, which it isn't...

![image](https://user-images.githubusercontent.com/271656/56867665-b7930580-69df-11e9-9083-0fc2844bdba0.png)

**Comment by ENikS** [comment]
I found an issue with the container and delayed the release.

**Comment by ENikS** [comment]
It is unlisted, I will list it again when rest of the packages are released

**Comment by PhilPJL** [comment]
Shouldn't abstractions 4.1.3 be marked as requiring container 5.11 in which case I wouldn't have been prompted to update until it was available (well hopefully).

**Comment by ENikS** [comment]
No, it should not
