### ISSUE TITLE
Issue with DependencyAttribute

### ISSUE THREAD

**Issue by michaelmairegger** [unitycontainer/abstractions#113]
I recently started updating this library to the newest version and noted the injecting into a non public property fails. Is this a regression issue or is this behavior wanted?

With an old version this code works, with the new no injection happens.
```C#
[Dependency]
protected IMyInterface DeletionService { get; set; }
```

I have seen the with v4 this line has changed https://github.com/unitycontainer/abstractions/blob/7247dd9a29e4207804804d1f3c2a868ef4f61308/src/Dependency/Injection/Members/InjectionProperty.cs#L57

**Comment by ENikS** [comment]
This behavior is by design and issue was discussed at length [here](https://github.com/unitycontainer/unity/issues/272).
