### ISSUE TITLE
Upgrade to 4.x+ - breaking change - constructor injection of AppSettings in config via IResolverPolicy

### ISSUE THREAD

**Issue by gccollect** [unitycontainer/abstractions#115]
### Description
Before 4.x it was possible to directly inject AppSettings values in constructors in the App.config using the code from https://weblogs.asp.net/ricardoperes/unity-part-5-injecting-values

### Problem
However this doesn't work anymore as Unity.Policy.IResolverPolicy as been removed in 4.0.  Being able to inject AppSettings directly from the config rather than the code is extremely convenient. Is there a way to do the same in 4.x?

### Impact
Unable to upgrade to latest version of Unity.

**Comment by ENikS** [comment]
Duplicate #109
