### ISSUE TITLE
Unity is not [assembly: SecurityTransparent] anymore 

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/abstractions#14]
@abramovandrey Wrote:
Please make Unity assemblies [SecurityTransparent] (at least lifetime managers) as it was in 4.0.1
Moved from unitycontainer/unity#130

**Comment by ENikS** [comment]
I fixed it in code. Will deploy with Unity.Abstractions.2.0.2 in about a week.

**Comment by abramovandrey** [comment]
Thank you!

**Comment by ENikS** [comment]
You could build and sign locally and use it until official release
