### ISSUE TITLE
ResolveAll is broken

### ISSUE THREAD

**Issue by brianlagunas** [unitycontainer/abstractions#17]
I believe you have introduced a breaking change in which the UnityCOntainerExtensions.ResolveAll does not call the correct method.  See: https://github.com/unitycontainer/abstractions/blob/master/src/Utility/UnityContainerExtensions.cs#L519

The line should read
`var result = (container ?? throw new ArgumentNullException(nameof(container))).ResolveAll((type ?? throw new ArgumentNullException(nameof(type`

The key method missing being **ResolveAll**.

This was discovered when Prism upgraded to v5 and our unit tests started failing.

**Comment by brianlagunas** [comment]
Actually, this looks like this is related to the interface of IUnityContainer changing, which seems to have broken Prism.  Still investigating.

**Comment by ENikS** [comment]
Could you be more specific: what is failing and under what circumstances. 
The code you referring to is working fine in all existing tests. Granted these are the original tests and only cover 87% of code...

Could you give me a test case where it fails?

**Comment by brianlagunas** [comment]
This test fails: https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Unity.Wpf.Tests/UnityServiceLocatorAdapterFixture.cs#L34

This actually seems to be related to the fact that the IUnityContainer interface was changed.  ResolveAll is no longer on the interface, which means the new extension method is being used instead of the interface method (which has been removed), hence breaking our tests.  I have updated the issue.

Do you have a list of all the breaking changes you have made?

**Comment by ENikS** [comment]
Looking at the coverage date I can see it is being tested properly: https://codecov.io/gh/unitycontainer/unity/src/master/src/Unity/Container/UnityContainerExtensions.cs

**Comment by ENikS** [comment]
I listed all breaking changes in release notes every time there was a change.

**Comment by brianlagunas** [comment]
I don't see them:  https://github.com/unitycontainer/abstractions/releases

Should I be looking somewhere else?

**Comment by ENikS** [comment]
I see the problem. Mocks will not work.

**Comment by ENikS** [comment]
https://github.com/unitycontainer/unity/releases

**Comment by brianlagunas** [comment]
I see... I will have to find a way to update my tests to account for all the breaking changes.
