### ISSUE TITLE
Unity.Abstractions 5.11.6 not working with Unity.AspNet.WebApi 5.0.15?

### ISSUE THREAD

**Issue by rcdailey** [unitycontainer/abstractions#183]
I want to upgrade `Unity.Container` and `Unity.Abstractions`, but I do not want to upgrade `Unity.AspNet.WebApi`, since that will require me to go down a rabbit hole upgrading ASP.NET and other Microsoft nuget packages.

When I compile, I get this error:

>   [CS0012] The type 'IUnityContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Abstractions, Version=3.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f'.

According to [NuGet Gallery for Unity.AspNet.WebApi v5.0.15](https://www.nuget.org/packages/Unity.AspNet.WebApi/5.0.15), it requires any version of `Unity.Abstractions` equal to or greater than 3.3.1. So this should work just fine. Nuget versioning drives me absolutely nuts, so I'd appreciate any help figuring this out (or figure out if it's truly a bug).

Here's the version numbers in my `Directory.Build.targets`:

```
    <PackageReference Update="Unity.AspNet.WebApi" Version="5.0.15" />
    <PackageReference Update="Unity.Container" Version="5.11.8" />
    <PackageReference Update="Unity.Abstractions" Version="5.11.6" />
```

**Comment by ENikS** [comment]
You could try to get source for Unity.AspNet.WebApi v5.0.15 and recompile against the latest. You'll have your local package pointing to the latest Unity.

**Comment by rcdailey** [comment]
Sure I can do that, then I guess I'd just keep the output DLL in my repo and use that in the meantime? Do you happen to know why the packages don't just work in the first place?

Thanks for your quick response!

**Comment by ENikS** [comment]
NuGet does pretty tricky version juggling behind the scene. Hard to say what is wrong without looking at the actual project.
