### ISSUE TITLE
PerSessionLifetimeManager no longer works after upgrading to Unity.Abstraction 5.11

### ISSUE THREAD

**Issue by CrestApps** [unitycontainer/abstractions#186]
### Description

I just upgraded `Unity.Abstraction` from 4.1.0 to 5.11.6, `Unity.Mvc` from 5.9.2 to 5.11.1, and `Unity.Container` from 5.9.7 to 5.11.1. 

I need to be able to register objects per user's session. I had the following custom `LifetimeManager` which was working fine in before the upgrade, but it is no longer working now. 

Here is my custom implementation of the `LifetimeManager`

```
    public class PerSessionLifetimeManager : LifetimeManager, IInstanceLifetimeManager, IFactoryLifetimeManager, ITypeLifetimeManager
    {
        private string _key = Guid.NewGuid().ToString();

        public override void RemoveValue(ILifetimeContainer container = null)
        {
            HttpContext.Current.Session.Remove(_key);
        }

        public override void SetValue(object newValue, ILifetimeContainer container = null)
        {
            HttpContext.Current.Session[_key] = newValue;
        }

        public override object GetValue(ILifetimeContainer container = null)
        {
            return HttpContext.Current.Session[_key];
        }

        protected override LifetimeManager OnCreateLifetimeManager()
        {
            return new PerSessionLifetimeManager();
        }
    }
```

I tried to register my object like so

```
container.RegisterFactory<IFlashManager>(_ => new FlashManager(), new PerSessionLifetimeManager());
```

I also tried to register

```
container.RegisterType<IFlashManager, FlashManager>(new PerSessionLifetimeManager());
```

However, when I try to resolve the `IFlashManager` using constructor injection, I get `null`. Before the upgrade, an instance of the `FlashManager` would be resolved.

How can I correct this issue and create per-session lifetime-manager?

**Comment by ENikS** [comment]
Your manager is returning 'null' as invalid value. It should return [LifetimeManager.NaValue](https://github.com/unitycontainer/abstractions/blob/2b99c9686bc01c3ef22ef294ec3afd558b4cb994/src/Lifetime/Abstracts/LifetimeManager.cs#L17) constant.

In current version 'null' is valid value.

**Comment by CrestApps** [comment]
@ENikS I am not sure I follow the instruction.

**Comment by ENikS** [comment]
Do like this:
```C#
public override object GetValue(ILifetimeContainer container = null)
{
    return HttpContext.Current.Session[_key] ?? LifetimeManager.NaValue;
}
```

**Comment by CrestApps** [comment]
Thank you! That indeed fixed it
