### ISSUE TITLE
XML documentation question

### ISSUE THREAD

**Issue by basarugur** [unitycontainer/abstractions#197]
Is there a reason why XML documentation is _not_ generated and attached to the Nuget packages? To be more specific, why is the `GenerateDocumentationFile` property (set to `true`) _not_ introduced in the [Unity.Abstractions.csproj](https://github.com/unitycontainer/abstractions/blob/master/src/Unity.Abstractions.csproj) file, along with a `DocumentationFile` property to provide the output file name? This actually applies to the [Container project](https://github.com/unitycontainer/container/blob/master/src/Unity.Container.csproj) too.

**Comment by ENikS** [comment]
No good reason. Just need someone to do it.
