### ISSUE TITLE
How to return the old behaviour of Unity registration/resolve processes

### ISSUE THREAD

**Issue by ashelemba** [unitycontainer/abstractions#198]
Example for Unity 2.1    

        container.RegisterType<ISomeClass, SomeClass>(new InjectionConstructor(new A()));
        var sc = container.Resolve<SomeClass>();

Here we will successfully resolve SomeClass and it will have A in the constructor.

Example for Unity 5.1
   

        container.RegisterType<ISomeClass, SomeClass>(new InjectionConstructor(new A()));
        var sc = container.Resolve<SomeClass>();

Here the same code will throw an exception, since SomeClass is not registered explicitly. It will only work if written like this

        container.RegisterType<SomeClass>(new InjectionConstructor(new A()));
        var sc = container.Resolve<SomeClass>();

Is it possible to somehow return the old behavior of version 2.1?

**Comment by ENikS** [comment]
Old code created two internal registrations: 
a registration `RegisterType<SomeClass>(new InjectionConstructor(new A()))` 
and a mapping `RegisterType<ISomeClass, SomeClass>()` 

A new engine, as an optimization, creates only one registration `RegisterType<ISomeClass, SomeClass>(new InjectionConstructor(new A()))`. In short, there is no way to go back to legacy registration scheme.
