### ISSUE TITLE
Add container 'owned' transient lifetime manager ContainerControlledTransientManager

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/abstractions#37]
Normally Unity container does not keep track of created transient objects. It creates them and forgets them. In certain situations it is useful to make container remember all transient objects it have created.

So, ``ContainerControlledTransientManager`` is required. This lifetime manager is the same as ``TransientLifetimeManager`` except if the object implements ``IDisposable`` it will keep **strong** reference to object and dispose it when container is disposed.
If created object is not disposable, container does not maintain any object references so when that object is released GC will collect it immediately.

**Comment by soeron** [comment]
Hello,
Great work with the container so far. Is this something like this https://thorarin.net/blog/post/2013/02/12/Unity-IoC-lifetime-management-IDisposable-part1.aspx extension?
If not do you have any guidance how to convert the extension to the new version?

**Comment by ENikS** [comment]
ContainerControlledTransientManager is what the blog calls DisposingTransientLifetimeManager. It can be used without any extensions.
DisposedShared could be done as ContainerControlledLifetimeManager.

There are no teardown in Unity anymore, but it all should work with properly scoped child containers
