### ISSUE TITLE
InjectionFactory not being called for interface registrations

### ISSUE THREAD

**Issue by mchamler** [unitycontainer/abstractions#41]
The registration looks something like this:

container.RegisterType<IFoo, Foo>(new InjectionFactory(cont => FooFactory.Create()));

When resolving IFoo the InjectionFactory isn't being called, which results in an InvalidOperationException: "The type Foo does not have an accessible constructor."

Looking at the registration in the debugger, I see the "IFoo" registration has two IBuilderPolicy values associated:
1. IBuildPlanPolicy => ResolveBuildUpPolicy
2. IBuildKeyMappingPolicy => BuildKeyMappingPolicy

I was expecting to find a registration like "IBuildPlanPolicy => InjectionFactory"

**Comment by mchamler** [comment]
The workaround for this problem is to split up the interface and type registrations. So, the above example would become:
container.RegisterType<Foo>(new InjectionFactory(cont => FooFactory.Create()));
container.RegisterType<IFoo, Foo>();

I think this is a pretty dangerous bug. If Foo had a public constructor this would have been a silent bug as Foo might be resolved with the wrong state. I've actually found other places in my app where that's exactly what is happening.

**Comment by ENikS** [comment]
https://github.com/unitycontainer/unity/releases/tag/5.2.1.311

**Comment by mchamler** [comment]
If it's not supported, it should throw an exception. It was supported before, so this is a silent breaking change. The current behavior isn't even reasonable, since the call succeeds, but the InjectionFactory is simply dropped from the registration.

**Comment by ENikS** [comment]
It had been discussed [here](https://github.com/unitycontainer/unity/issues/201)
