### ISSUE TITLE
Could not load file or assembly 'Unity.Abstractions'

### ISSUE THREAD

**Issue by Mario1159** [unitycontainer/abstractions#85]
I had my unity composite package before without a problem but now without modifying my code i get this exception "Could not load file or assembly 'Unity.Abstractions', Version 3.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' ...".
I just can start my application when i change my AssemblyInfo.cs, for example changing AssemblyFileVersion or other property, but after closing and starting my app again, the exception throws again.

**Comment by ENikS** [comment]
I would recommend linking to individual packages. Just link to Unity.Container and NuGet will do the rest.
