### ISSUE TITLE
Named dependency resolver overrides

### ISSUE THREAD

**Issue by DoctorVanGogh** [unitycontainer/abstractions#87]
I have a problem in UnityContainer I cannot seem to solve.
```cs

class Foo {
  Foo ([OptionalDependency("fred")] object x, 
       [OptionalDependency("george")] object y)
}
```
As far as I could figure out you cannot supply distinct `ResolverOverrides` for `x` & `y` _unless_ you choose to use  `ParameterOverride` with the specific parameter names.
I find this incredibly brittle, since there's no programmatic way to make sure code referencing those parameters stays synchronized with the actual _names_ of the parameters.

I _could_ add those values as properties, which at least would leave me the option of using `nameof(Foo.X)` in a `PropertyOveride`, but I don't really want those values to be mutable.

What I _want_ to do, is something like `NamedDependencyOverride<object>("fred", 42)`, `NamedDependencyOverride<object>("george", 17)` since the depependency _names_ are actually constants which I can keep synchronized.

Currently the only way to do something similar seems to be using `CreateChildContainer` and doing named registrations in there before doing a resolve but I'm concerned about performance implications of creating lots of child containers per execution.

Am I missing something or is this feature actually not available?

**Comment by ENikS** [comment]
[Take a look](https://github.com/unitycontainer/specification-tests/blob/vNext/src/Resolution/Overrides/Dependency.cs), let me know if I should add something else
