### ISSUE TITLE
Replace InjectionFactory with explicit method on IUnityContainer

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/abstractions#89]
### Description
Currently to provide factory for the type you have to create ``InjectionFactory`` and pass it to the ``RegisterType`` method.

### Problem
This method has inherent inefficiencies built into it. It requires allocating instance of ``InjectionFactory`` ,  during registration. It also allocates resolution policy to wrap it and provide 'glue' to be called by the Container.

Another issue it does not participate in sharing Per-Resolve dependencies during resolution process. 

### Solution
Create new method called ``RegisterFactory`` to allow registration of the factory delegate.

**Comment by karelkral** [comment]
Please document how to use replacement methods for InjectionFactory. I am using InjectionFactory in many places.

**Comment by ENikS** [comment]
I thought it is self explanatory. Instead of calling RegisterType with InjectionFactory as parameter, you pass your factory delegate to RegisterFactory method.

Would you like to contribute proper help wiki?

**Comment by kajbonfils** [comment]
Yes, please provide a help wiki with an example on how to use it.

**Comment by ENikS** [comment]
It will be some time...
I am working on the documentation project

**Comment by hypercodeplace** [comment]
Hi @ENikS,
It will be good to be able to pass `resolver overrides` to the factory too. I have a real production scenario to use it. Am I right it's not possible to pass it for now?

**Comment by ENikS** [comment]
Could you create a unit test with the scenario so I can look at it?

**Comment by jwahr** [comment]
> Please document how to use replacement methods for InjectionFactory. I am using InjectionFactory in many places.

I am in the same boat

**Comment by jwahr** [comment]
So I have three examples of our usage and I am not quite sure on how to replace them with `container.RegisterFactory`. I am new to Unity and I am just trying to update our solution to the latest. Any help would be greatly appreciated :)

**Updating from and to:**
`Unity 5.8.11 => 5.9.7`
`Unity.Abstractions 3.3.1.0 => 4.1.0.0`
`Unity.AspNet.WebApi 5.0.15 => 5.9.2`
`Unity.Container 5.8.11.0 => 5.9.7.0`

**Added:**
`Unity.Configuration 5.9.2`


**Sample 1:**
```
container.RegisterType<ISettingsProvider>(
    new InjectionFactory(x => new BasicSettingsProvider(ConfigurationManager.AppSettings)));
```

**Sample 2:**
```
container.RegisterType<SiteDataContext>(
    new InjectionFactory(unityContainer =>
    {
        var context = OwinRequestScopeContext.Current;
        if (context != null && context.Items.ContainsKey(TenantDataContextKey))
            return (SiteDataContext)context.Items[TenantDataContextKey];

        var appTenant = SampleContext.Current.GetOwinContext().GetTenantContext<AppTenant>().AppTenant;
        var connectionString = ConnectionStringBuilder
            .GetSiteConnectionString(TenantHelper.CatalogName(appTenant.Tenant), TenantHelper.LoginName(appTenant.Tenant));

        var dataContext = new SiteDataContext(connectionString);

        if (context != null)
            context.Items[TenantDataContextKey] = dataContext;

        return dataContext;
    }));
```

**Sample 3:**
```
container
    .RegisterType<MapperConfiguration>(
        new ContainerControlledLifetimeManager(),
        new InjectionFactory(c =>
            new MapperConfiguration(configuration =>
            {
                configuration.ConstructServicesUsing(t => container.Resolve(t));
                foreach (var profile in container.FindAndResolveAllImplementationsOf<Profile>())
                    configuration.AddProfile(profile);
            })))
    .RegisterType<IConfigurationProvider>(
        new ContainerControlledLifetimeManager(),
        new InjectionFactory(c => c.Resolve<MapperConfiguration>()))
    .RegisterType<IMapper>(
        new InjectionFactory(c => c.Resolve<MapperConfiguration>().CreateMapper()));
```

**Comment by ENikS** [comment]
All you need to do is to call RegisterFactory and pass a delegate. No need to create a wrapper.
```
container.RegisterFactory<ISettingsProvider>((container, type, name)=>
   new BasicSettingsProvider(ConfigurationManager.AppSettings));
```
