### ISSUE TITLE
pls add  public static IUnityContainer RegisterType<TFrom, TTo>(this IUnityContainer container, LifetimeManager lifetimeManager, params InjectionMember[] injectionMembers) where TTo : TFrom;

### ISSUE THREAD

**Issue by neozhu** [unitycontainer/abstractions#91]
### Description
container.RegisterType<IUnitOfWorkAsync, UnitOfWork>(new PerRequestLifetimeManager(), null);
container.RegisterType<DbContext, StoreContext>(new PerRequestLifetimeManager(), null);
 ### To Reproduce
new version not Implement public static IUnityContainer RegisterType<TFrom, TTo>(this IUnityContainer container, LifetimeManager lifetimeManager, params InjectionMember[] injectionMembers) where TTo : TFrom;

```C#
 
```

**Additional context**

pls add

**Comment by ENikS** [comment]
Duplicate unitycontainer/aspnet-mvc#10
