### ISSUE TITLE
UnityContainerExtensions class exists in both Unity.Container and Unity.Abstractions under the same namespace

### ISSUE THREAD

**Issue by bhalbright** [unitycontainer/abstractions#95]
### Description

I updated to Unity 5.9.1 from Nuget and starting getting compile errors in code that uses UnityContainerExtensions:

The type 'UnityContainerExtensions' exists in both 'Unity.Abstractions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0' and 'Unity.Container, Version=5.9.1.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0'	Avecto.IC3.Infrastructure.Core	C:\dev\Avecto\iC3\Avecto.IC3.Portal\Avecto.AMP.Infrastructure.Core\Container.cs	106	Active

Indeed I can see this class defined in the same namespace in both libraries:

- https://github.com/unitycontainer/container/blob/e078166387c12118d895607550bdf7348d32c8de/src/Extensions/UnityContainerExtensions.cs

- https://github.com/unitycontainer/abstractions/blob/fbc8a427ef552b12b724f436109c22a2f62bd408/src/Extensions/Container/UnityContainer.cs

Or am I doing something wrong? I'm guessing I will add an extern alias to avoid this conflict, but wanted to report it.

**Comment by ENikS** [comment]
Thank you for your help!
