### ISSUE TITLE
v5.8.x vs v5.9.x shared injection member leads to incorrect type resolution

### ISSUE THREAD

**Issue by snekbaev** [unitycontainer/abstractions#96]
Hi,

after upgrade noticed that app started crashing at run-time. It was failing to resolve the correct type for certain registrations. Upon investigation it seemed that using shared injection instance leads to this problem:

```
var commonConstructor = new InjectionConstructor( flurlClientFactory, settings, objectMapper );

unityContainer.RegisterType<IPersonService, PersonService>( instance.Name, new ContainerControlledLifetimeManager(), commonConstructor );
unityContainer.RegisterType<IMembershipService, MembershipService>( instance.Name, new ContainerControlledLifetimeManager(), commonConstructor );
// more similar...
```
so basically after all these registrations if I do ```unityContainer.Resolve<IPersonService>("xyz")``` it will return the **last** registered type instead of the correct one. In the example above that would be ```MembershipService```

Solution is to stop using the shared injection member and refactor to:

```
unityContainer.RegisterType<IPersonService, PersonService>( instance.Name, new ContainerControlledLifetimeManager(), new InjectionConstructor( flurlClientFactory, settings, objectMapper ) );
unityContainer.RegisterType<IMembershipService, MembershipService>( instance.Name, new ContainerControlledLifetimeManager(), new InjectionConstructor( flurlClientFactory, settings, objectMapper ) );
```

Maybe it would be beneficial to catch cases like this one earlier, say, during registration by checking the reference equality?

Thank you!

**Comment by ENikS** [comment]
This check will only be available in Diagnostic mode.
