### ISSUE TITLE
How to upgrade to v4+

### ISSUE THREAD

**Issue by rikrak** [unitycontainer/abstractions#97]
### Description

I've upgraded my Unity.Abstractions references from v3.3.0 to v4.1.0 (along with other related unity packages) and there appears to be some breaking changes.  

At the moment I'm not sure how to go about fixing my code; Is there any upgrade guidance available?
(I've spent the morning googling around, but not found anything so far, but I may be using the wrong search terms :-) )

**Comment by ENikS** [comment]
The latest has some breaking charges.

As for guidance, would you like to write about your experience updating?

You can help others and I can answer your questions along the way.

**Comment by Ronosho** [comment]
I have the same problem.

I'm using `new ParameterOverrides` for a 
`public static T Retrieve<T>(params ResolverOverride[] parameterOverride)
        {
            return Containter.Resolve<T>(parameterOverride);
        }`
method. 
This no longer works with the new version as it's unable to resolve the method.
Any pointers for this?

**Comment by ENikS** [comment]
Posting a unit test with failing code would be a good start

**Comment by Ronosho** [comment]
After upgrading the code no longer compiles, I have yet found a way to fix my code to build

**Comment by ENikS** [comment]
@Ronosho 

I would assume it is similar to [this one](https://github.com/unitycontainer/unity/issues/278#issuecomment-472158999)

**Comment by rikrak** [comment]
I'll add my Build issues (and solutions) one at a time on this thread for others to benefit from :-)

### Problem:
Build error
`The type or namespace name 'IBuilderContext' could not be found`

### Solution:
`IBuilderContext` has been replaced with:  `Unity.Builder.BuilderContext`

**Comment by rikrak** [comment]
### Problem:
Build Error
`'IBuildPlanCreatorPolicy' is obsolete: 'This interface has been replaced with  Unity.Policy.ResolveDelegateFactory delegate'`	

### Solution
TBC

**Comment by rikrak** [comment]
### Problem:
Build Error in BuilderStrategy derived classes:
`'MyCustomStrategy.PreBuildUp(BuilderContext)': no suitable method found to override`	

### Solution:
Adjust the signature of the `PreBuildUp` method to:
`public override void PreBuildUp(ref BuilderContext context)`

**Comment by rikrak** [comment]
### Problem:

Build Error in BuilderStrategy derived classes:
`'MyCustomStrategy.PostBuildUp(BuilderContext)': no suitable method found to override`

### Solution:

Adjust the signature of the `PostBuildUp` method to:
`public override void PreBuildUp(ref BuilderContext context)`

**Comment by ENikS** [comment]
@rikrak 
For IBuildPlanCreatorPolicy I can suggest [this example](https://github.com/unitycontainer/examples/blob/master/src/Extending%20Unity/BuildPlanCreator/FooBuildPlanCreatorPolicy.cs)

**Comment by rikrak** [comment]
### Problem:
Build Error in Builder Strategy derived class:
`'BuilderContext' does not contain a definition for 'AddResolverOverrides' and no accessible extension method 'AddResolverOverrides' accepting a first argument of type 'BuilderContext' could be found`

### Solution:
TBC

**Comment by rikrak** [comment]
### Problem:
`'BuilderContext' does not contain a definition for 'ParentContext' and no accessible extension method 'ParentContext' accepting a first argument of type 'BuilderContext' could be found`

I used the ParentContext of IBuilderContext to determine if anything in the build hierarchy was of a certain type.  More specifically I was checking to see if a specific decorator class was being applied as part of the build.

### Solution:
There is an `IntPtr Parent` property on the `BuilderContext` struct.  Can this be used to find the parent context?

**Comment by rikrak** [comment]
### Problem:
There is a build warning:
`'InjectionFactory' is obsolete: 'InjectionFactory has been deprecated and will be removed in next release. Please use IUnityContainer.RegisterFactory(...) method instead.'` 

### Solution:
The InjectionFactory class has been deprecated.  Injection factories are now registered directly with the container.
For example:

**Old code:**
`Container.RegisterType<IEncryptionProvider>(new ContainerControlledLifetimeManager(), new InjectionFactory(c => MakeEncryptionProvider(c)));`

**New code:**
`Container.RegisterFactory<IEncryptionProvider>(c => MakeEncryptionProvider(c), new ContainerControlledLifetimeManager());`

**Comment by rikrak** [comment]
### Be Aware:
The public key token of the assembly has changed, so you may need to remove redundant assembly bindings from config files.

For example:
This binding will now be ineefective, and can be removed:
```
      <dependentAssembly>
        <assemblyIdentity name="Unity.Abstractions" publicKeyToken="6d32ff45e0ccc69f" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
      </dependentAssembly>
```
Note: 

- the old public key token value is `6d32ff45e0ccc69f`
- the new public key token is `489b6accfaf20ef0`

**Comment by Ronosho** [comment]
### Problem
I'm using this code to register my interfaces.
`Containter.RegisterType<ICustomerRepository, CustomerRepository>(new ContainerControlledLifetimeManager(), InjectionConstructor);`

but after the upgrade im getting the following error when resolving
```
Exception thrown: 'System.InvalidCastException' in Unity.Abstractions.dll
Unable to cast object of type
```

**Comment by rikrak** [comment]
@Ronosho Could you provide a bit more detail?  The code you've provided doesn't compile for me.
I tried my own example (see below), which works fine for me:

```C#
public class Tests
    {
        [TestMethod]
        public void ShouldResolveAlternativeImplementationWhenUsingOverride()
        {
            // arrange
            var target = new UnityContainer();
            target
                .RegisterType<IController, TheController>(new ContainerControlledLifetimeManager(), new InjectionConstructor(new AlternativeMessageProvider()))
                .RegisterType<IMessageProvider, DefaultMessageProvider>()
                ;

            // act
            var actual = target.Resolve<IController>(); 

            // assert
            Assert.AreEqual(actual.GetMessage(), "Goodbye cruel world!");
        }
    }

    public interface IController
    {
        string GetMessage();
    }

    public class TheController : IController
    {
        private readonly IMessageProvider _messageProvider;

        public TheController(IMessageProvider messageProvider)
        {
            _messageProvider = messageProvider;
        }

        public string GetMessage()
        {
            return _messageProvider.CalculateMessage();
        }
    }

    public interface IMessageProvider
    {
        string CalculateMessage();
    }

    class DefaultMessageProvider : IMessageProvider
    {
        public string CalculateMessage()
        {
            return "Hello World";
        }
    }

    class AlternativeMessageProvider : IMessageProvider
    {
        public string CalculateMessage()
        {
            return "Goodbye cruel world!";
        }
    }
```

**Comment by rikrak** [comment]
### Problem:

Build Error in BuilderStrategy derived classes:
'MyCustomStrategy.PostBuildUp(BuilderContext)': no suitable method found to override

### Solution:

Adjust the signature of the `PostBuildUp` method to:
`public override void PreBuildUp(ref BuilderContext context)`

**Comment by Ronosho** [comment]
### Solution

Ok I managed to find out what I was doing wrong.
I was reussing the same InjectionConstructor for all my registrations.
After replacing them with a new instance for each my problem went away.

**Comment by ENikS** [comment]
@Ronosho 

Enabling [Diagnostic extension](https://github.com/unitycontainer/container/blob/master/src/Extension/Diagnostic.cs) should have helped you. It suppose to throw on injectors reuse.

```c#
var container = new UnityContainer();
container.EnableDiagnostic();
...
```
This extension method only works in DEBUG mode.

**Comment by Ronosho** [comment]
@ENikS I did not realize we could do that, thanks.
Was the injectors reuse a recent change?

**Comment by ENikS** [comment]
It changed in 5.9.0

**Comment by ENikS** [comment]
@rikrak 

The flow of issues seems to be drying out. Are you closer to finishing your upgrage?

**Comment by rikrak** [comment]
Think so. The Dependency Resollver bug I logged with the Container should
help. I'm hoping to complete the work tomorrow or the day after.

**Comment by rikrak** [comment]
I've upgraded my solution today, and all looks good.  This issue can be closed.
Many thanks for your help @ENikS :-)

**Comment by MousekeAcknowledge** [comment]
I'm currently upgrading all my NuGet packages in our solution, I'm not familiar with Unity at all but upgrading gave some breaking issues, I solved some but this one I cannot seem to figure out.

`container.RegisterType<ICommunicationService>(
                new InjectionFactory(cont =>
                {
                    string refreshToken = HttpContext.Current.Request.Cookies[AccountClient.RefreshTokenCookieName]?.Value;
                    return new CommunicationService(cont.Resolve<IRequestBuilderService>(),
                                                    cont.Resolve<IConfigService>(),
                                                    LogManager.GetLogger("Log"),
                                                    cont.Resolve<AuthenticationHeaderValue>(),
                                                    refreshToken);
                }),
                new Interceptor<InterfaceInterceptor>(),
                new InterceptionBehavior<LogInterceptor>());`

The application tells me this 'InjectionFactory' is obsolete: 'InjectionFactory has been deprecated and will be removed in next release. Please use IUnityContainer.RegisterFactory(...) method instead.', I had several other RegisterType calls but replaced them all with RegisterFactory. But there seem to be no RegisterFactory for InjectionMembers.

`public static IUnityContainer RegisterType<T>(this IUnityContainer container, params InjectionMember[] injectionMembers);`

I'm currently suppressing it but I would rather fix it.

**Comment by ENikS** [comment]
You do not pass any injection members to injection factory.

**Comment by BishSum** [comment]
Can any one implemented the below functionality in New Version. I am pretty new to Unity if you can guide how to achieve below behavior. Thanks 


Source https://mikaelkoskinen.net/post/unity-passing-constructor-parameters-to-resolve


public class OrderedParametersOverride : ResolverOverride
{
    private readonly Queue<InjectionParameterValue> parameterValues;
 
    public OrderedParametersOverride(IEnumerable<object> parameterValues)
    {
        this.parameterValues = new Queue<InjectionParameterValue>();
        foreach (var parameterValue in parameterValues)
        {
            this.parameterValues.Enqueue(InjectionParameterValue.ToParameter(parameterValue));
        }
    }
 
    public override IDependencyResolverPolicy GetResolver(IBuilderContext context, Type dependencyType)
    {
        if (parameterValues.Count < 1)
            return null;
 
        var value = this.parameterValues.Dequeue();
        return value.GetResolverPolicy(dependencyType);
    }
}

**Comment by Farami** [comment]
What happened to `DependencyOverrides` and `PropertyOverrides`? They seem to be gone in v4+.

**Comment by roblapp** [comment]
The number of changes in each Unity version is out of control. Many breaking changes with little to no documentation.

**Comment by ENikS** [comment]
Writing documentation is not my strongest skill. Would you like to help improving the docs?
Or perhaps you could sponsor hiring a technician writer?
