### ISSUE TITLE
5.9.8+ (Changes?): Align ResolverOverride class names & functionalities

### ISSUE THREAD

**Issue by DoctorVanGogh** [unitycontainer/abstractions#99]
With the advertised behavior (changes?) for 5.9.8+ from unitycontainer/container#140 I think there is at least a bit of a misnomer in type names:

![image](https://user-images.githubusercontent.com/324067/54676636-61d65e00-4b01-11e9-8670-f10061c6ae44.png)

While all `ResolverOverride`s may in fact override _dependencies_, an actual `DependencyOverride` will only override a _resolution_ ([See](https://unitycontainer.github.io/tutorials/resolution/Overrides/dependency.html)). 

The actual _functionality_ and _naming_ here are completely inverted. That behavior is certainly unexpected.

This warrants a design pass (maybe for 6.0?).

**Comment by ENikS** [comment]
Would you like to contribute better tutorial for the type? I am still working on the documentation and would appreciate any help.

**Comment by ENikS** [comment]
Hmm, I guess not
